### ISSUE TITLE
Setting variable inside loop after it is read is declared as unused

### ISSUE THREAD

**Issue by triwav** [rokucommunity/bslint#67] opened 2022-05-09 18:28 UTC
Take the example 
```
myValue = initialValue
while true
  if myValue = invalid
    exit while
  else if otherStuff
  end if

  myValue = getValue()
end while
```
the line `myValue = getValue()` will be declared as unused when it will be used during the next loop.

**Comment by elsassph** [comment] 2022-10-04 06:42
Right, we have the same problem with `goto` loops.

**Comment by elsassph** [comment] 2022-10-04 06:42
duplicate of #66

**Closed by elsassph** 2022-10-04 06:42 UTC
Labels: bug
